# Generated by Django 2.2.24 on 2021-07-02 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210702_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user',
            new_name='owner',
        ),
    ]
